-- Intentionally empty.
--
-- Production and shared Supabase environments must not seed ventures, research
-- findings, simulations, investor sessions, or historical test ideas. A venture
-- enters the ventures table only through an explicit real-user create action.
--
-- Tests that need venture data must use isolated fixtures/mocks or disposable
-- test records that are cleaned up by the test itself. Do not add demo/sample
-- venture INSERTs here.
