-- No seed data for Slice 1: workspaces are created automatically for each
-- new auth user via the handle_new_user trigger in 0001_init.sql. Seeded
-- demo scenarios (Coquitlam marketplace, AI nail design app — spec §22.2)
-- land with the slices that actually use them.
