export type MonetizationContext = { geography?: string | null; audience?: string | null; product?: string | null; pricingModel?: string | null; monthlyCost?: number | null; hasCompetitorPricing: boolean };
export type MonetizationExperiment = { key: string; title: string; hypothesis: string; fit: string; evidence: string[]; unknowns: string; metric: string; pricingModelOverride?: "subscription"|"one_time" };
export function createMonetizationExperiments(c: MonetizationContext): MonetizationExperiment[] {
  const audience=c.audience||"the intended audience"; const geo=c.geography||"the chosen market"; const cost=c.monthlyCost==null?"No Build Studio cost estimate exists yet.":`Build Studio estimates a $${c.monthlyCost}/month operating-cost floor.`;
  const pricing=c.hasCompetitorPricing?"Connected competitor pricing evidence is available.":"Competitor price evidence does not exist in connected sources.";
  return [
    {key:"monthly-annual",title:"Monthly vs annual",hypothesis:`An annual option may improve committed revenue from ${audience} without removing a lower-commitment monthly path.`,fit:`Useful when ${c.pricingModel==="subscription"?"a subscription is already selected":"recurring value is still an open assumption"}.`,evidence:[cost,pricing],unknowns:"Willingness to commit, discount sensitivity, and renewal behavior are unknown.",metric:"Paid conversion and 90-day retained revenue",pricingModelOverride:"subscription"},
    {key:"one-time-recurring",title:"One-time purchase vs recurring",hypothesis:`A one-time purchase may reduce adoption friction in ${geo}; recurring pricing may better support ongoing costs.`,fit:`Tests whether ${audience} perceives continuing or finite value in this product.`,evidence:[cost,pricing],unknowns:"No willingness-to-pay interviews or transaction data are connected.",metric:"Contribution margin per acquired user",pricingModelOverride:"one_time"},
    {key:"trial-paywall",title:"Trial vs no trial",hypothesis:"A short, useful trial may make the value clear before payment without creating indefinite free usage.",fit:`Relevant to the saved use case: ${c.product||"product details have not been shaped"}.`,evidence:[pricing],unknowns:"Activation moment and time-to-value are not measured yet.",metric:"Trial-to-paid conversion after activation"},
    {key:"regional",title:"Regional pricing",hypothesis:`A locally tested price for ${geo} may convert better than a single global price.`,fit:"Geography is venture context, but purchasing-power and tax evidence must be validated before setting a price.",evidence:[pricing],unknowns:"Local willingness to pay, taxes, currency fees, and platform rules are unknown.",metric:"Net revenue per eligible visitor by region"},
  ];
}
